name: login_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  flutter_native_splash: ^2.3.1
  get: ^4.6.5
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  email_validator: ^2.1.17
  font_awesome_flutter: ^10.5.0
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.8.4
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f671"
  dark_color: "#272727"
  image: assets/images/pizza-logo.png
  image_dark: assets/images/pizza-logo.png

  android_12:
    image: assets/images/pizza-logo.png
    icon_background_color: "#f7f671"
    image_dark: assets/images/pizza-logo.png
    icon_background_color_dark: "#272727"


flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'
    - 'assets/images/on_boarding_images/'
    - 'assets/images/profile_images/'
    - 'assets/logo/'

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
